<?php

namespace Database\Seeds\Locations;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
	{
		Country::insert([
			[ 'name' => 'Afeganistão', 'nationality' => 'Afegão' ],
			[ 'name' => 'Andorra', 'nationality' => 'Andorrano' ],
			[ 'name' => 'Angola', 'nationality' => 'Angolano' ],
			[ 'name' => 'Antígua e Barbuda', 'nationality' => 'Antiguano' ],
			[ 'name' => 'Argélia', 'nationality' => 'Argelino' ],
			[ 'name' => 'Argentina', 'nationality' => 'Argentino' ],
			[ 'name' => 'Armênia', 'nationality' => 'Armênio' ],
			[ 'name' => 'Austrália', 'nationality' => 'Australiano' ],
			[ 'name' => 'Áustria', 'nationality' => 'Austríaco' ],
			[ 'name' => 'Azerbaijão', 'nationality' => 'Azeri' ],
			[ 'name' => 'Bahamas', 'nationality' => 'Bahamense' ],
			[ 'name' => 'Bangladesh', 'nationality' => 'Bangladês' ],
			[ 'name' => 'Barbados', 'nationality' => 'Barbadiano' ],
			[ 'name' => 'Barém', 'nationality' => 'Baremita' ],
			[ 'name' => 'Bielorrússia', 'nationality' => 'Bielorrusso' ],
			[ 'name' => 'Bélgica', 'nationality' => 'Belga' ],
			[ 'name' => 'Belize', 'nationality' => 'Belizenho' ],
			[ 'name' => 'Benim', 'nationality' => 'Beninense' ],
			[ 'name' => 'Bolívia', 'nationality' => 'Boliviano' ],
			[ 'name' => 'Bósnia; Bósnia e Herzegovina', 'nationality' => 'Bósnio' ],
			[ 'name' => 'Botsuana', 'nationality' => 'Bechuano' ],
			[ 'name' => 'Brasil', 'nationality' => 'Brasileiro' ],
			[ 'name' => 'Brunei', 'nationality' => 'Bruneano' ],
			[ 'name' => 'Bulgária', 'nationality' => 'Búlgaro' ],
			[ 'name' => 'BurkinaFaso', 'nationality' => 'Burquinense' ],
			[ 'name' => 'Burundi', 'nationality' => 'Burundês' ],
			[ 'name' => 'Butão', 'nationality' => 'Butanense' ],
			[ 'name' => 'Cabo Verde', 'nationality' => 'Cabo-Verdiano' ],
			[ 'name' => 'Camarões', 'nationality' => 'Camaronense' ],
			[ 'name' => 'Camboja', 'nationality' => 'Cambojano' ],
			[ 'name' => 'Canadá', 'nationality' => 'Canadense' ],
			[ 'name' => 'República Centro-Africana', 'nationality' => 'Centroafricano' ],
			[ 'name' => 'Chade', 'nationality' => 'Chadiano' ],
			[ 'name' => 'China', 'nationality' => 'Chinês' ],
			[ 'name' => 'Chile', 'nationality' => 'Chileno' ],
			[ 'name' => 'Ilhas Cook', 'nationality' => 'Cookiano' ],
			[ 'name' => 'Colômbia', 'nationality' => 'Colombiano' ],
			[ 'name' => 'Comores', 'nationality' => 'Comoriano' ],
			[ 'name' => 'Costa Rica', 'nationality' => 'Costa-Riquenho' ],
			[ 'name' => 'Croácia', 'nationality' => 'Croata' ],
			[ 'name' => 'Cuba', 'nationality' => 'Cubano' ],
			[ 'name' => 'Chipre', 'nationality' => 'Cipriota' ],
			[ 'name' => 'República Tcheca', 'nationality' => 'Tcheco' ],
			[ 'name' => 'República Democrática do Congo', 'nationality' => 'Congolense' ],
			[ 'name' => 'Dinamarca', 'nationality' => 'Dinamarquês' ],
			[ 'name' => 'Djibuti', 'nationality' => 'Djibutiense' ],
			[ 'name' => 'Dominica', 'nationality' => 'Dominiquense' ],
			[ 'name' => 'República Dominicana', 'nationality' => 'Dominicano' ],
			[ 'name' => 'Timor Leste', 'nationality' => 'Timorense' ],
			[ 'name' => 'Equador', 'nationality' => 'Equatoriano' ],
			[ 'name' => 'Egito', 'nationality' => 'Egípcio' ],
			[ 'name' => 'ElSalvador', 'nationality' => 'Salvadorenho' ],
			[ 'name' => 'Inglaterra', 'nationality' => 'Inglês' ],
			[ 'name' => 'Guiné Equatorial', 'nationality' => 'Guinéu-Equatoriano' ],
			[ 'name' => 'Eritreia', 'nationality' => 'Eritreu' ],
			[ 'name' => 'Estônia', 'nationality' => 'Estoniano' ],
			[ 'name' => 'Fiji', 'nationality' => 'Fijiano' ],
			[ 'name' => 'Finlândia', 'nationality' => 'Finlandês' ],
			[ 'name' => 'França', 'nationality' => 'Francês' ],
			[ 'name' => 'Gabão', 'nationality' => 'Gabonense' ],
			[ 'name' => 'Gâmbia', 'nationality' => 'Gambiano' ],
			[ 'name' => 'Geórgia', 'nationality' => 'Geórgico' ],
			[ 'name' => 'Alemanha', 'nationality' => 'Alemão' ],
			[ 'name' => 'Granada', 'nationality' => 'Granadino' ],
			[ 'name' => 'Grécia', 'nationality' => 'Grego' ],
			[ 'name' => 'Guatemala', 'nationality' => 'Guatemalteco' ],
			[ 'name' => 'Guiné', 'nationality' => 'Guineano' ],
			[ 'name' => 'GuinéBissau', 'nationality' => 'Guineense' ],
			[ 'name' => 'Guiana', 'nationality' => 'Guianense' ],
			[ 'name' => 'Haiti', 'nationality' => 'Haitiano' ],
			[ 'name' => 'Holanda', 'nationality' => 'Holandês' ],
			[ 'name' => 'Honduras', 'nationality' => 'Hondurenho' ],
			[ 'name' => 'Hungria', 'nationality' => 'Húngaro' ],
			[ 'name' => 'Islândia', 'nationality' => 'Islandês' ],
			[ 'name' => 'Índia', 'nationality' => 'Indiano' ],
			[ 'name' => 'Indonésia', 'nationality' => 'Indonésio' ],
			[ 'name' => 'Irã', 'nationality' => 'Iraniano' ],
			[ 'name' => 'Irlanda', 'nationality' => 'Irlandês' ],
			[ 'name' => 'Israel', 'nationality' => 'Israelita' ],
			[ 'name' => 'Itália', 'nationality' => 'Italiano' ],
			[ 'name' => 'Costa do Marfim', 'nationality' => '' ],
			[ 'name' => 'Jamaica', 'nationality' => 'Jamaicano' ],
			[ 'name' => 'Japão', 'nationality' => 'Japonês' ],
			[ 'name' => 'Jordânia', 'nationality' => 'Jordão' ],
			[ 'name' => 'Cazaquistão', 'nationality' => 'Cazaque' ],
			[ 'name' => 'Quênia', 'nationality' => 'Queniano' ],
			[ 'name' => 'Quiribati', 'nationality' => 'Quiribatiano' ],
			[ 'name' => 'Quirguistão', 'nationality' => 'Quirguistanês' ],
			[ 'name' => 'Kuwait', 'nationality' => 'Kuwaitiano' ],
			[ 'name' => 'Laos', 'nationality' => 'Laosiano' ],
			[ 'name' => 'Letônia', 'nationality' => 'Letoniano' ],
			[ 'name' => 'Líbano', 'nationality' => 'Libanês' ],
			[ 'name' => 'Lesoto', 'nationality' => 'Lesotiano' ],
			[ 'name' => 'Libéria', 'nationality' => 'Liberiano' ],
			[ 'name' => 'Liechtenstein', 'nationality' => 'Liechtensteinense' ],
			[ 'name' => 'Lituânia', 'nationality' => 'Lituano' ],
			[ 'name' => 'Luxemburgo', 'nationality' => 'Luxemburguês' ],
			[ 'name' => 'Líbia', 'nationality' => 'Líbio' ],
			[ 'name' => 'Macedônia', 'nationality' => 'Macedônio' ],
			[ 'name' => 'Madagascar', 'nationality' => 'Madagascarense' ],
			[ 'name' => 'Malásia', 'nationality' => 'Malaio' ],
			[ 'name' => 'Malaui', 'nationality' => 'Malauiano' ],
			[ 'name' => 'Maldivas', 'nationality' => 'Maldivo' ],
			[ 'name' => 'Máli', 'nationality' => 'Maliano' ],
			[ 'name' => 'Malta', 'nationality' => 'Maltês' ],
			[ 'name' => 'Maurício', 'nationality' => 'Mauriciano' ],
			[ 'name' => 'Mauritânia', 'nationality' => 'Mauritano' ],
			[ 'name' => 'Ilhas Marshall', 'nationality' => 'Marshallino' ],
			[ 'name' => 'Estados Federados da Micronésia', 'nationality' => 'Micronésio' ],
			[ 'name' => 'México', 'nationality' => 'Mexicano' ],
			[ 'name' => 'Marrocos', 'nationality' => 'Marroquino' ],
			[ 'name' => 'Moldavia', 'nationality' => 'Moldávio' ],
			[ 'name' => 'Mônaco', 'nationality' => 'Monegasco' ],
			[ 'name' => 'Mongólia', 'nationality' => 'Mongol' ],
			[ 'name' => 'Montenegro', 'nationality' => 'Montenegrino' ],
			[ 'name' => 'Moçambique', 'nationality' => 'Moçambicano' ],
			[ 'name' => 'Myanmar', 'nationality' => 'Birmanês' ],
			[ 'name' => 'Namíbia', 'nationality' => 'Namibiano' ],
			[ 'name' => 'Nauru', 'nationality' => 'Nauruano' ],
			[ 'name' => 'Nepal', 'nationality' => 'Nepalês' ],
			[ 'name' => 'NovaZelândia', 'nationality' => 'Neozelandês' ],
			[ 'name' => 'Nicarágua', 'nationality' => 'Nicaraguense' ],
			[ 'name' => 'Níger', 'nationality' => 'Nigerino' ],
			[ 'name' => 'Nigéria', 'nationality' => 'Nigeriano' ],
			[ 'name' => 'Niue', 'nationality' => 'Niuano' ],
			[ 'name' => 'Coréia do Norte', 'nationality' => 'Norte-Coreano' ],
			[ 'name' => 'Noruega', 'nationality' => 'Norueguês' ],
			[ 'name' => 'Omã', 'nationality' => 'Omanense' ],
			[ 'name' => 'Palestina', 'nationality' => 'Palestino' ],
			[ 'name' => 'Paquistão', 'nationality' => 'Paquistanês' ],
			[ 'name' => 'Palau', 'nationality' => 'Palauense' ],
			[ 'name' => 'Panamá', 'nationality' => 'Panamenho' ],
			[ 'name' => 'Papua Nova Guiné', 'nationality' => 'Papuásio' ],
			[ 'name' => 'Paraguai', 'nationality' => 'Paraguaio' ],
			[ 'name' => 'Peru', 'nationality' => 'Peruano' ],
			[ 'name' => 'Philippines', 'nationality' => 'Filipino' ],
			[ 'name' => 'Polônia', 'nationality' => 'Polonês' ],
			[ 'name' => 'Portugal', 'nationality' => 'Português' ],
			[ 'name' => 'Catar', 'nationality' => 'Catarense' ],
			[ 'name' => 'Romênia', 'nationality' => 'Romeno' ],
			[ 'name' => 'Rússia', 'nationality' => 'Russo' ],
			[ 'name' => 'Ruanda', 'nationality' => 'Ruandês' ],
			[ 'name' => 'Samoa', 'nationality' => 'Samoano' ],
			[ 'name' => 'SantaLucia', 'nationality' => 'Santa-Lucense' ],
			[ 'name' => 'São Cristóvão e Nevis', 'nationality' => 'São-Cristovense' ],
			[ 'name' => 'São Marino', 'nationality' => 'São-Marinense' ],
			[ 'name' => 'São Tomé e Príncipe', 'nationality' => 'São-Tomense' ],
			[ 'name' => 'São Vicente e Granadinas', 'nationality' => 'São-Vicentino' ],
			[ 'name' => 'Escócia', 'nationality' => 'Escocês' ],
			[ 'name' => 'Senegal', 'nationality' => 'Senegalense' ],
			[ 'name' => 'Sérvia', 'nationality' => 'Servio' ],
			[ 'name' => 'Seicheles', 'nationality' => 'Seichelense' ],
			[ 'name' => 'Serra Leoa', 'nationality' => 'Serra-Leonês' ],
			[ 'name' => 'Singapura', 'nationality' => 'Singapurense' ],
			[ 'name' => 'Eslováquia', 'nationality' => 'Eslovaco' ],
			[ 'name' => 'Ilhas Salomão', 'nationality' => 'Salomônico' ],
			[ 'name' => 'Somália', 'nationality' => 'Somali' ],
			[ 'name' => 'África do Sul', 'nationality' => 'Sul-Africano' ],
			[ 'name' => 'Coréia do Sul', 'nationality' => 'Coreano' ],
			[ 'name' => 'Sudão do Sul', 'nationality' => 'Sul-Sudanense' ],
			[ 'name' => 'Espanha', 'nationality' => 'Espanhol' ],
			[ 'name' => 'Sri Lanka', 'nationality' => 'Srilankês' ],
			[ 'name' => 'Sudão', 'nationality' => 'Sudanense' ],
			[ 'name' => 'Suriname', 'nationality' => 'Surinamês' ],
			[ 'name' => 'Suazilândia', 'nationality' => 'Suazi' ],
			[ 'name' => 'Suécia', 'nationality' => 'Sueco' ],
			[ 'name' => 'Suíça', 'nationality' => 'Suíço' ],
			[ 'name' => 'Síria', 'nationality' => 'Sírio' ],
			[ 'name' => 'Tadiquistão', 'nationality' => 'Tajique' ],
			[ 'name' => 'Tanzânia', 'nationality' => 'Tanzaniano' ],
			[ 'name' => 'Tailândia', 'nationality' => 'Tailandês' ],
			[ 'name' => 'Togo', 'nationality' => 'Togolês' ],
			[ 'name' => 'Tonga', 'nationality' => 'Tonganês' ],
			[ 'name' => 'TrindadeeTobago', 'nationality' => 'Trinitário' ],
			[ 'name' => 'Tunísia', 'nationality' => 'Tunisiano' ],
			[ 'name' => 'Turcomenistão', 'nationality' => 'Turcomeno' ],
			[ 'name' => 'Turquia', 'nationality' => 'Turco' ],
			[ 'name' => 'Tuvalu', 'nationality' => 'Tuvaluano' ],
			[ 'name' => 'Ucrânia', 'nationality' => 'Ucraniano' ],
			[ 'name' => 'Uganda', 'nationality' => 'Ugandês' ],
			[ 'name' => 'Uruguai', 'nationality' => 'Uruguaio' ],
			[ 'name' => 'Emirados Árabes Unidos', 'nationality' => 'Árabe' ],
			[ 'name' => 'Reino Unido', 'nationality' => 'Britânico' ],
			[ 'name' => 'Estados Unidos', 'nationality' => 'Americano' ],
			[ 'name' => 'Usbequistão', 'nationality' => 'Uzbeque' ],
			[ 'name' => 'Vanuatu', 'nationality' => 'Vanuatuano' ],
			[ 'name' => 'Venezuela', 'nationality' => 'Venezuelano' ],
			[ 'name' => 'Vietnã', 'nationality' => 'Vietnamita' ],
			[ 'name' => 'País de Gales', 'nationality' => 'Galês' ],
			[ 'name' => 'Iêmen', 'nationality' => 'Iemenita' ],
			[ 'name' => 'Zâmbia', 'nationality' => 'Zambiano' ],
			[ 'name' => 'Zimbábue', 'nationality' => 'Zimbabueano' ]
		]);
    }
}
